### ISSUE TITLE
表结构缺少吧

### ISSUE THREAD

**Issue by hapacc** [loyer-yuan/REMVocabulary#1]
(1146, "Table 'remvocabulary_dbms.user' doesn't exist")
--

**Comment by loyer-yuan** [comment]
你得先建一个remvocabulary_dbms的数据库，然后执行sql文件夹下的sql文件，才有对应的表 #1

**Comment by loyer-yuan** [comment]
> 你得先建一个remvocabulary_dbms的数据库，然后执行sql文件夹下的sql文件，才有对应的表

**Comment by hapacc** [comment]
大佬，上传单词本出bug了，是因为我系统的缘故吗？
[![ohNrNR.md.png](https://s1.ax1x.com/2021/12/09/ohNrNR.md.png)](https://imgtu.com/i/ohNrNR)

**Comment by hapacc** [comment]
[![o4naND.png](https://s1.ax1x.com/2021/12/09/o4naND.png)](https://imgtu.com/i/o4naND)
大佬，点击上传单词本后，显示如图。并未成功添加单词本，选词页面和学习界面均未显示单词。

**Comment by loyer-yuan** [comment]
这不是有提示嘛，就是有不在单词库的单词呀，没上传成功。单词上传需要txt格式，一行一个单词

**Comment by hapacc** [comment]
上传的就是TXT，就是默认里的CET6那个，就是一行一个。

**Comment by loyer-yuan** [comment]
哦，这个原因啊，我说的是要一行只能有1个单词，不能有中文等其他信息，你使用CET-en那个单词本上传

**Comment by loyer-yuan** [comment]
我这个程序当初为了赶课设的时间，没有来得及做太多的输入验证

**Comment by hapacc** [comment]
是的，就是那个一行只有1个单词，且无中文。

**Comment by loyer-yuan** [comment]
那我不知道该怎么解决，因为我这里的话，是有中文才没有相应的提示，如果只有1个单词，单词库中不存在该单词，会在界面中显示出来，然后把这个单词删掉就可以了

**Comment by hapacc** [comment]
好的 感谢大佬耐心解答～

**Comment by Kete24** [comment]
你好，请问  这个新创建的用户为什么无法上传单词本

**Comment by loyer-yuan** [comment]
这个项目已经很久远了，我已经不维护了。里面逻辑不复杂，可以自行理解。
